### ISSUE TITLE
CentOS 5 support

### ISSUE THREAD

**Issue by JorisVanEijden** [geerlingguy/ansible-role-samba#1]
CentOS 5 needs packages samba3x, samba3x-common and samba3x-winbind because the base samba packages are incompatible with cifs-utils.

**Comment by geerlingguy** [comment]
@JorisVanEijden Unfortunately, I don't think I'll be adding in CentOS 5 support to this role, just because I can't easily test back further than 6 and it'll be (finally) reaching EOL sometime soon...
