### ISSUE TITLE
Fails under Ubuntu 20.04 due to missing packages

### ISSUE THREAD

**Issue by mattj65817** [geerlingguy/ansible-role-samba#11]
I'm relatively new to Ansible, so bear with me if I'm missing some critical details that make my suggestion unworkable, BUT...

Attempting to use this role to manage Samba on an Ubuntu 20.04 server, I receive this error:
```
TASK [geerlingguy.samba : Ensure Samba-related packages are installed (Debian).] ***************************************
failed: [clus0-node0-apct11.local] (item=['samba', 'samba-common', 'python-glade2', 'system-config-samba']) => {"ansible_loop_var": "item", "changed": false, "item": ["samba", "samba-common", "python-glade2", "system-config-samba"], "msg": "No package matching 'python-glade2' is available"}
```
Further, if the reference to `python-glade2` is removed from the task, a subsequent attempt also fails due to removal of the `system-config-samba` package. So, my educated guess is that these two packages have been removed from Ubuntu 20.04 completely.

The task works fine if I remove these packages and update the task to *only* install the `samba` package, allowing apt to resolve any other dependencies. I don't know whether the absence of `python-glade2` will cause problems further down the line, however, so this may not be a workable solution to the problem?

**Comment by geerlingguy** [comment]
I haven't yet tested this role under 20.04, but my guess/hope is that samba doesn't require these packages anymore in 20.04. See related issue in Ubuntu's tracker: https://bugs.launchpad.net/ubuntu/+source/pygtk/+bug/1876276

**Comment by mattj65817** [comment]
@geerlingguy yep, that's the issue. It sure seems to work fine if you remove them from the task, for what that's worth.
