### ISSUE TITLE
system-config-samba not available in Debian

### ISSUE THREAD

**Issue by SiggyF** [geerlingguy/ansible-role-samba#4]
The package `system-config-samba` is not available in [debian](https://packages.debian.org/search?keywords=system-config-samba&searchon=names&suite=all&section=all), raspbian and probably some other variants. I believe it was added in ubuntu. 
Shall I submit a pull request to install cifs-utils instead? Then the centos and debian roles install the same packages. `cifs-utils` is available since wheezy

**Comment by geerlingguy** [comment]
@SiggyF - Makes sense to me. I could've sworn I had tested this role on my Pi at one point, but I guess not :)

**Comment by geerlingguy** [comment]
If you submit a PR, can you please add a test to the Travisfile for Debian 8? Just like this: https://github.com/geerlingguy/ansible-role-firewall/blob/master/.travis.yml#L20-L22
